[project]

name = "phangsPipeline"
dynamic = ["version"]
description = "PHANGS-ALMA Pipeline"
readme = "README.md"
requires-python = ">=3.12, <3.13"
license = {file = "LICENSE"}

authors = [
    {name = "PHANGS Team"},
]

# Alphabetically
maintainers = [
    {name = "Eric Koch", email = "koch.eric.w@gmail.com"},
    {name = "Adam Leroy", email = "leroy.42@osu.edu"},
    {name = "Daizhong Liu", email = "astro.dzliu@gmail.com"},
    {name = "Erik Rosolowsky", email = "rosolowsky@ualberta.ca"},
    {name = "Jiayi Sun", email = "astrojysun@outlook.com"},
    {name = "Thomas Williams", email = "thomas.g.williams@manchester.ac.uk"},
]

classifiers = [
    "Development Status :: 5 - Production/Stable",

    # License
    "License :: OSI Approved :: MIT License",

    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3 :: Only",
]

dependencies = [
    "astropy >= 7.2.0",
    "astroquery >= 0.4.11",
    "convolve_uv >= 0.2.0",
    "matplotlib >= 3.10.9",
    "numpy >= 2.3.5",
    "protobuf == 3.20",
    "pytz >= 2025.2",
    "radio-beam >= 0.3.9",
    "reproject >= 0.21.0",
    "scipy >= 1.16.3",
    "spectral-cube == 0.6.7",
    "uvcombine >= 1.0.0",
]

# Optional packages for CASA
[project.optional-dependencies]
casa = [
    "casadata >= 2025.9.22",
    "casaplotms >= 2.8.2",
    "casarecipes >= 0.4.0",
    "casashell >= 6.7.3.21, < 6.7.6.14",
    "casatasks >= 6.7.3.21, < 6.7.6.14",
    "casatools >= 6.7.3.21, < 6.7.6.14",
    "casaviewer >= 2.4.4 ; platform_system != 'Darwin'",
    "pipeline@git+https://open-bitbucket.nrao.edu/scm/pipe/pipeline.git",
]

# Optional packages for the test suite
test = [
    "pytest-cov >= 7.1.0",
]
test-casa = [
    "zenodo-get >= 3.0.0",
]
test-ruff = [
    "ruff >= 0.15.10",
]

# Optional packages for documentation
docs = [
    "myst-parser >= 5.1.0",
    "sphinx >= 9.1.0",
    "sphinx-automodapi >= 0.22.0",
    "sphinx-rtd-theme >= 3.1.0",
]

[project.urls]
"Homepage" = "https://github.com/phangsTeam/phangs_imaging_scripts"
"Bug Reports" = "https://github.com/phangsTeam/phangs_imaging_scripts/issues"
"Source" = "https://github.com/phangsTeam/phangs_imaging_scripts"

[tool.setuptools.packages.find]
exclude = [
    "phangs-alma_keys/*",
    "scripts/*",
]

# Omit in coverage. Notably here, we exclude
# the CASA analysisutils
[tool.coverage.run]
omit = [
    "docs/*",
    "phangs-alma_keys/*",
    "tests/*",
    "*/analysis_scripts/*",
]

[tool.coverage.report]
exclude_lines = [
    'except ImportError',
    'except ModuleNotFoundError',
    'except \(ImportError, ModuleNotFoundError\)',
    'raise AssertionError',
    'raise NotImplementedError',
]

[build-system]
requires = [
    "setuptools >= 80.9.0",
    "setuptools_scm >= 9.2.2",
    "wheel >= 0.45.1",
]

build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
# Configure custom options here (version schemes, file writing, etc.)
version_file = "phangsPipeline/version.py"
