name: Build

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  job:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [
          '3.12',
        ]
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install .
          pip install .[casa]
      - name: Build package
        run: python -m build
